### ISSUE TITLE
Camera doesn't work...

### ISSUE THREAD

**Issue by renildo393** [chiteroman/kernel_vayu#2]
![Screenshot_20240322-105804_Câmera](https://github.com/chiteroman/kernel_vayu/assets/76791050/e6676012-9018-43be-b43c-8322dcfc32ad)

I tested the open camera and the Leica camera....And the same problem persists.

Derpfest, a13(180923), poco x3 pro, ksu(0.9.2(11682))

**Comment by ChickenNuggetScientist** [comment]
Try clearing cache and data for leica camera mod and start the app again

**Comment by chiteroman** [comment]
> Try clearing cache and data for leica camera mod and start the app again

Nope, that's a driver problem. That it's kernel problem, I will fix it asap.

**Comment by renildo393** [comment]
Problem solved here... With this new kernel update, the camera started working normally again...
